import RootClient from "@/components/RootClient";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <RootClient>
          {children}
        </RootClient>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ConsentProvider } from "@/components/Consent";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         {/* Consent goes here */}
//         <ConsentProvider
//           config={{
//             languages: ["en", "pl"],
//             legalVersion: "2024-08-02",
//             categories: {
//               necessary: { required: true },
//               analytics: { default: false },
//               marketing: { default: false },
//             },
//             onUpdate: (s) => console.log("state", s),
//           }}
//         />
//         {children}
//       </body>
//     </html>
//   );
// }
